name: Build

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Build
        run: dotnet build PGS.sln
